Solution/ExtendedSearch/ExtendedSearch/Controllers/SearchConfigurationController.cs
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ExtendedSearch.Data;
using PagedList;

namespace ExtendedSearch.Controllers
{
	public class SearchConfigurationController : Controller
	{
		private readonly ExtendedSearchEntities _extendedSearchContext;

		public SearchConfigurationController()
		{
			_extendedSearchContext = new ExtendedSearchEntities();
		}

		public SearchConfigurationController(ExtendedSearchEntities extendedSearchContext)
		{
			_extendedSearchContext = extendedSearchContext;
		}

		public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
		{
			ViewBag.CurrentSort = sortOrder;
			ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

			if (searchString != null)
			{
				page = 1;
			}
			else
			{
				searchString = currentFilter;
			}

			ViewBag.CurrentFilter = searchString;

			var searchDataContext = new SearchData(_extendedSearchContext);
			var engines = searchDataContext.GetSearchEngines();

			if (!string.IsNullOrEmpty(searchString))
			{
				engines = engines.Where(s => s.EngineName.ToLower().Contains(searchString.ToLower()));
			}
			switch (sortOrder)
			{
				case "name_desc":
					engines = engines.OrderByDescending(s => s.EngineName);
					break;
				default:
					engines = engines.OrderBy(s => s.EngineName);
					break;
			}

			int pageSize = 5;
			int pageNumber = (page ?? 1);
			return View(engines.ToPagedList(pageNumber, pageSize));
		}

		public ActionResult Details(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			var searchDataContext = new SearchData(_extendedSearchContext);
			var engine = searchDataContext.GetEngine(id.Value);
			
			if (engine == null)
			{
				return HttpNotFound();
			}
			return View(engine);
		}

		public ActionResult Create()
		{
			return View();
		}

		
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "EngineName, Url")]Engine engine)
		{
			try
			{
				if (ModelState.IsValid)
				{
					var searchDataContext = new SearchData(_extendedSearchContext);
					var engineList = searchDataContext.AddEngine(engine);
					if (engineList != null)
					{
						return RedirectToAction("Index");
					}
					ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
				}
			}
			catch (RetryLimitExceededException)
			{
				ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
			}
			return View(engine);
		}


		public ActionResult Edit(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			var searchDataContext = new SearchData(_extendedSearchContext);
			var engine = searchDataContext.GetEngine(id.Value);

			if (engine == null)
			{
				return HttpNotFound();
			}
			return View(engine);
		}

		
		[HttpPost, ActionName("Edit")]
		[ValidateAntiForgeryToken]
		public ActionResult EditPost(Engine model)
		{
			if (model == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			try
			{
				var searchDataContext = new SearchData(_extendedSearchContext);
				var engineList = searchDataContext.UpdateEngine(model);
				if (engineList != null)
				{
					return RedirectToAction("Index");
				}

				ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
				
			}
			catch (RetryLimitExceededException)
			{
				ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
			}
			
			return View(model);
		}

		
		public ActionResult Delete(int? id, bool? saveChangesError = false)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			if (saveChangesError.GetValueOrDefault())
			{
				ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
			}

			var searchDataContext = new SearchData(_extendedSearchContext);
			var engine = searchDataContext.GetEngine(id.Value);
			
			if (engine == null)
			{
				return HttpNotFound();
			}
			return View(engine);
		}

		
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id)
		{
			try
			{
				var searchDataContext = new SearchData(_extendedSearchContext);
				var engineList = searchDataContext.DeleteEngine(id);
				return engineList != null ? RedirectToAction("Index") : RedirectToAction("Delete", new { id, saveChangesError = true });
			}
			catch (RetryLimitExceededException)
			{
				return RedirectToAction("Delete", new { id, saveChangesError = true });
			}
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				_extendedSearchContext.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

Solution/ExtendedSearch/ExtendedSearch/Views/SearchConfiguration/Create.cshtml
@using System.Web.Optimization
@model ExtendedSearch.Engine

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EngineName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EngineName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EngineName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Solution/ExtendedSearch/ExtendedSearch/Views/SearchConfiguration/Delete.cshtml
@model ExtendedSearch.Engine

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<p class="error">@ViewBag.ErrorMessage</p>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EngineName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EngineName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Solution/ExtendedSearch/ExtendedSearch/Views/SearchConfiguration/Details.cshtml
@model ExtendedSearch.Engine

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Engine Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayFor(model => model.EngineName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>
       
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Solution/ExtendedSearch/ExtendedSearch/Views/SearchConfiguration/Edit.cshtml
@using System.Web.Optimization
@model ExtendedSearch.Engine

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Engine</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.EngineName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EngineName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EngineName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Solution/ExtendedSearch/ExtendedSearch/Views/SearchConfiguration/Index.cshtml
@model PagedList.IPagedList<ExtendedSearch.Engine>
	@using PagedList.Mvc;
	<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
	@{
		ViewBag.Title = "Search Configuration";
	}

	@section featured
{
		<section class="featured">
			<div class="content-wrapper">
				<hgroup class="title">
					<h1>@ViewBag.Title.</h1>
			</div>
		</section>
	}
						   	<h2>Engines</h2>

						   	<p>
						   		@Html.ActionLink("Create New", "Create")
						   </p>
						   @using (Html.BeginForm("Index", "SearchConfiguration", FormMethod.Get))
						   {
						   	<p>
						   		Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
						   <input type="submit" value="Search" />
						   </p>
						   }
						   <table class="table">
						   	<tr>
						   		<th>
						   			@Html.ActionLink("Engine Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
						   </th>
						   <th>
						   	Url
						   </th>
						   <th>
						   </th>
						   <th></th>
						   </tr>


						   @foreach (var item in Model)
						   {
						   	<tr>
						   		<td>
						   			@Html.DisplayFor(modelItem => item.EngineName)
						   </td>
						   <td>
						   	@Html.DisplayFor(modelItem => item.Url)
						   </td>

						   <td>
						   	@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
						   @Html.ActionLink("Details", "Details", new { id = item.Id }) |
						   @Html.ActionLink("Delete", "Delete", new { id = item.Id })
						   </td>
						   </tr>
						   }

						   </table>
						   <br />
						   Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

						   @Html.PagedListPager(Model, page => Url.Action("Index",
	new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))