Solution/ExtendedSearch/ExtendedSearch/Models/SearchViewModel.cs
namespace ExtendedSearch.Models
{
	public class SearchViewModel
	{
		public int Id { get; set; }
		public string EngineName { get; set; }
		public string SearchFor { get; set; }
		public string SearchResult { get; set; }
	}
}

Solution/ExtendedSearch/ExtendedSearch/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using ExtendedSearch.Data;
using ExtendedSearch.Models;

namespace ExtendedSearch.Controllers
{
	public class SearchController : Controller
	{
		private readonly ExtendedSearchEntities _extendedSearchContext;

		public SearchController()
		{
			_extendedSearchContext = new ExtendedSearchEntities();
		}

		public SearchController(ExtendedSearchEntities extendedSearchContext)
		{
			_extendedSearchContext = extendedSearchContext;
		}

		public ActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public async Task<JsonResult> GetResult(SearchInput term)
		{
			try
			{
				var searchDataContext = new SearchData(_extendedSearchContext);
				var listOfSe = searchDataContext.GetSearchEngines();
				var downloadTasks = listOfSe.Select(searchEngine => ProcessSe(term.Searchinput, searchEngine.EngineName, searchEngine.Url)).ToList();
				var firstFinishedTask = await Task.WhenAny(downloadTasks);
				var responseList = await firstFinishedTask;
				var searchResult = responseList.Response;
				var msg = responseList.EngName;
				var engine = searchDataContext.GetEngineByName(msg);
				searchDataContext.StoreSearchResult(term.Searchinput, engine.Id, searchResult);
				return Json(new { msg, searchResult });
			}
			catch (Exception ex)
			{
				return Json(new { ex.Message, string.Empty });
			}
		}

		private async Task<SearchResponce> ProcessSe(string term, string se, string url)
		{

			//if (se == "GoogleSe")
			//{
			//	await Task.Delay(1000);
			//}

			//if (se == "GoogleSe" || se == "BingSe")
			//{
			//	await Task.Delay(1000);
			//}

			return await Process(term, se, url);
		}

		private async Task<SearchResponce> Process(string term, string se, string url)
		{

			var gs = string.Format(url, term);

			var response = string.Empty;
			var httpWebRequest = WebRequest.Create(gs) as HttpWebRequest;

			if (httpWebRequest != null)
			{
				httpWebRequest.Method = WebRequestMethods.Http.Get;
				httpWebRequest.Headers.Add("Accept-Language", "en-US");
				httpWebRequest.UserAgent = "Mozilla/4.0 (compatible; MSIE 6.0; Win32)";
				httpWebRequest.Headers.Add(HttpRequestHeader.AcceptEncoding, "gzip,deflate");

				using (var httpWebResponse = httpWebRequest.GetResponse() as HttpWebResponse)
				{
					Stream stream;
					if (httpWebResponse == null) return new SearchResponce(response, se);
					using (stream = httpWebResponse.GetResponseStream())
					{
						if (httpWebResponse.ContentEncoding.ToLower().Contains("gzip"))
							stream = new GZipStream(stream, CompressionMode.Decompress);
						else if (httpWebResponse.ContentEncoding.ToLower().Contains("deflate"))
							stream = new DeflateStream(stream, CompressionMode.Decompress);

						var streamReader = new StreamReader(stream, Encoding.UTF8);
						response = streamReader.ReadToEnd();
					}
				}
			}

			//if (se == "GoogleSe")
			//{
			//	await Task.Delay(1000);
			//}

			//if (se == "GoogleSe" || se == "BingSe")
			//{
			//	await Task.Delay(1000);
			//}

			return new SearchResponce(response, se);
		}
		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				_extendedSearchContext.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

Solution/ExtendedSearch/ExtendedSearch/Views/Search/Index.cshtml
@{
    ViewBag.Title = "Search Engine";
}

@section featured
{
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>                
            </hgroup>
        </div>
    </section>    
}
<html lang="en">
<head>

	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<link rel="stylesheet" href="/resources/demos/style.css">
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	<script src="https://code.jquery.com/jquery-1.10.2.js"></script>

	<script>

		$(function() {
			// OPEN
			$('[data-popup-open]').on('click', function(e) {
				var search = getSearch();
				if (search == null) {
					alert("Specify search!");
					return false;
				}

				var json = JSON.stringify(search);

				debugger;

				$.ajax({
					url: '@Url.Action("GetResult", "Search")',
					type: 'POST',
					dataType: 'json',
					data: json,
					contentType: 'application/json; charset=utf-8',
					success: function(data) {

						var html = data.searchResult;
						var enghtml = data.msg;

						debugger;

						$("#EngResult").html(enghtml);
						$("#resultHtml").html(html);

						$("#resultHtml").dialog();

					},
					error: function(ex) {
						alert("error --->" + ex);
					}
				});


				function getSearch() {
					debugger;

					var searchinput = $("#srchterm").val();

					return { searchinput: searchinput };
				}

				var targeted_popup_class = jQuery(this).attr('data-popup-open');
				$('[data-popup="' + targeted_popup_class + '"]').fadeIn(350);
				e.preventDefault();

				return false;
			});

			// CLOSE
			$('[data-popup-close]').on('click', function(e) {
				var targeted_popup_class = jQuery(this).attr('data-popup-close');
				$('[data-popup="' + targeted_popup_class + '"]').fadeOut(350);

				e.preventDefault();
			});
		});
	</script>

</head>

<body>

	<form id="searchForm" class="body-content">
		<input id="srchterm" type="text" style="width: 500px" />
		<a class="btn" data-popup-open="popup-1" href="#">Search</a>
	</form>

	<div class="popup" data-popup="popup-1">
		<div class="popup-inner">
			<div id="EngResult"></div><div> search result</div>
			<a class="popup-close" data-popup-close="popup-1" href="#">x</a>
			<p>
				<a data-popup-close="popup-1" href="#">Close</a>
			</p>

			<div id="resultHtml"></div>
		</div>
	</div>

</body>

</html>
       