Solution/ExtendedSearch/ExtendedSearch/Controllers/SearchResultsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ExtendedSearch.Data;
using ExtendedSearch.Models;
using PagedList;

namespace ExtendedSearch.Controllers
{
	public class SearchResultsController : Controller
	{
		private readonly ExtendedSearchEntities _extendedSearchContext;

		public SearchResultsController()
		{
			_extendedSearchContext = new ExtendedSearchEntities();
		}

		public SearchResultsController(ExtendedSearchEntities extendedSearchContext)
		{
			_extendedSearchContext = extendedSearchContext;
		}

		public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
		{
			ViewBag.CurrentSort = sortOrder;
			ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
			
			if (searchString != null)
			{
				page = 1;
			}
			else
			{
				searchString = currentFilter;
			}

			ViewBag.CurrentFilter = searchString;

			var searchDataContext = new SearchData(_extendedSearchContext);
			var searches = searchDataContext.GetSearchResults();

			if (!string.IsNullOrEmpty(searchString))
			{
				searches = searches.Where(s => s.SearchFor != null).Where(s => s.SearchFor.ToLower().Contains(searchString.ToLower())).ToList();
			}
			switch (sortOrder)
			{
				case "name_desc":
					searches = searches.OrderByDescending(s => s.SearchFor).ToList();
					break;
				default:
					searches = searches.OrderBy(s => s.SearchFor).ToList();
					break;
			}

			var pageSize = 5;
			var pageNumber = (page ?? 1);

			var viewResultModel = (from search in searches
				let engine = search.Engine.HasValue 
					? searchDataContext.GetEngine(search.Engine.Value) 
					: new Engine()
				where engine != null
				select new SearchViewModel
				{
					Id = search.Id,
					SearchFor = search.SearchFor,
					SearchResult = search.SearchResult,
					EngineName = search.Engine != null && searchDataContext.GetEngine(search.Engine.Value) != null 
						? engine.EngineName 
						: string.Empty
				}).ToList();

			return View(viewResultModel.ToPagedList(pageNumber, pageSize));
		}

		public ActionResult Details(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			var searchDataContext = new SearchData(_extendedSearchContext);
			var search = searchDataContext.GetSearchResultById(id.Value);
			
			if (search == null)
			{
				return HttpNotFound();
			}
			return View(search);
		}
	}
}

Solution/ExtendedSearch/ExtendedSearch/Views/SearchResults/Details.cshtml
@model ExtendedSearch.Search

@{
	ViewBag.Title = "Details";
}

<h2>Details</h2>
<br />
<br />


<div style="position: relative; overflow-y: scroll; height: 800px!important;">
	<h4>Search Details</h4>
	@Html.ActionLink("Back to List", "Index")
	<br />
	<br />
	@Html.Raw(Model.SearchResult)
</div>
<p>
	@Html.ActionLink("Back to List", "Index")
</p>

Solution/ExtendedSearch/ExtendedSearch/Views/SearchResults/Index.cshtml
@model PagedList.IPagedList<ExtendedSearch.Models.SearchViewModel>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

	@{
		ViewBag.Title = "Search Results";
	}

	@section featured
{
		<section class="featured">
			<div class="content-wrapper">
				<hgroup class="title">
					<h1>@ViewBag.Title.</h1>
				</hgroup>
			</div>
		</section>
	}
						   	<h2>Engines</h2>


						   	@using (Html.BeginForm("Index", "SearchResults", FormMethod.Get))
							{
						   	<p>
						   		Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
						   <input type="submit" value="Search" />
						   </p>
							}
						   <table class="table">
						   	<tr>
						   		<th>
						   			@Html.ActionLink("Search for", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
						   </th>
						   <th>
						   	Engine
						   </th>
						   <th>
						   </th>
						   <th></th>
						   </tr>


						   @foreach (var item in Model)
						   {
						   	<tr>
						   		<td>
						   			@Html.DisplayFor(modelItem => item.SearchFor)
						   </td>
						   <td>
						   	@Html.DisplayFor(modelItem => item.EngineName)
						   </td>
						   <td>
						   	@Html.ActionLink("Details", "Details", new { id = item.Id })
						   </td>

						   </tr>
						   }

						   </table>
						   <br />
						   Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

						   @Html.PagedListPager(Model, page => Url.Action("Index",
	new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))